"use client";

import { useState } from "react";
import { ArrowDown, ArrowUp, Check, CircleAlert, Eye, Loader2, Plus, Sparkles, Trash2 } from "lucide-react";

import { FormAlert } from "@/components/forms/form-alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Progress } from "@/components/ui/progress";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useApiMutation } from "@/hooks/use-api-mutation";
import { useApiQuery } from "@/hooks/use-api-query";
import { aiApi, materialApi, quizApi } from "@/lib/api/endpoints";
import { queryKeys } from "@/lib/api/query-keys";
import { cn } from "@/lib/utils";
import type { QuizDetail } from "@/types/entities";
import { blankQuestion, CHOICES, optionField, toDraft, toEditable, validateQuestion, type EditableQuestion } from "./question-model";
import { useNow } from "./use-clock";

const STAGES = ["Processing PDF", "Retrieving relevant content", "Creating MCQs", "Validating questions"];
const COUNTS = ["5", "10", "15", "20", "30"];
const DIFFICULTIES = [
  { value: "easy", label: "Easy" },
  { value: "medium", label: "Medium" },
  { value: "hard", label: "Hard" },
] as const;

/**
 * The teacher's question workspace: write or generate questions, review every
 * one, edit / reorder / delete, then save. Nothing generated by AI reaches
 * students without this review and a separate publish step.
 */
export function QuestionEditor({ quiz, editable }: { quiz: QuizDetail; editable: boolean }) {
  const [questions, setQuestions] = useState<EditableQuestion[]>(() => (quiz.questions ?? []).map((q) => toEditable(q)));
  const [savedJson, setSavedJson] = useState(() => JSON.stringify((quiz.questions ?? []).map((q) => toDraft(toEditable(q)))));
  const [previewing, setPreviewing] = useState(false);

  const errors = questions.map(validateQuestion);
  const hasErrors = errors.some(Boolean);
  const dirty = JSON.stringify(questions.map(toDraft)) !== savedJson;

  const save = useApiMutation({
    mutationFn: () => quizApi.saveQuestions(quiz.id, questions.map(toDraft)),
    successMessage: "Questions saved.",
    invalidate: [queryKeys.quiz.detail(quiz.id), queryKeys.course.quizzes(quiz.courseOfferingId)],
    onSuccess: () => setSavedJson(JSON.stringify(questions.map(toDraft))),
  });

  const update = (key: string, patch: Partial<EditableQuestion>) =>
    setQuestions((list) => list.map((q) => (q.key === key ? { ...q, ...patch } : q)));
  const remove = (key: string) => setQuestions((list) => list.filter((q) => q.key !== key));
  const move = (index: number, delta: -1 | 1) =>
    setQuestions((list) => {
      const target = index + delta;
      if (target < 0 || target >= list.length) return list;
      const next = [...list];
      [next[index], next[target]] = [next[target], next[index]];
      return next;
    });

  return (
    <div className="space-y-6">
      {editable ? <AiGenerator quiz={quiz} onGenerated={(generated) => setQuestions((list) => [...list, ...generated])} /> : null}

      <div className="flex flex-wrap items-center gap-3">
        <h2 className="text-base font-semibold">
          Questions <span className="text-muted-foreground font-normal">({questions.length})</span>
        </h2>
        {editable && dirty ? <Badge variant="outline" className="border-warning text-amber-800 dark:text-warning">Unsaved changes</Badge> : null}
        <div className="ml-auto flex flex-wrap gap-2">
          <Button variant="outline" size="sm" disabled={questions.length === 0} onClick={() => setPreviewing(true)}>
            <Eye className="size-4" aria-hidden="true" /> Preview
          </Button>
          {editable ? (
            <>
              <Button variant="outline" size="sm" onClick={() => setQuestions((list) => [...list, blankQuestion()])}>
                <Plus className="size-4" aria-hidden="true" /> Add question
              </Button>
              <Button size="sm" disabled={!dirty || hasErrors || save.isPending} onClick={() => save.mutate()} className="bg-brand-gradient text-white hover:opacity-90">
                {save.isPending ? (
                  <>
                    <Loader2 className="size-4 animate-spin" aria-hidden="true" /> Saving…
                  </>
                ) : (
                  "Save questions"
                )}
              </Button>
            </>
          ) : null}
        </div>
      </div>

      {editable && hasErrors && dirty ? (
        <p role="status" className="text-muted-foreground text-sm">
          Fix the highlighted questions to save.
        </p>
      ) : null}

      {questions.length === 0 ? (
        <div className="bg-muted/40 rounded-xl border border-dashed px-6 py-10 text-center text-sm text-muted-foreground">
          {editable ? "No questions yet. Generate them from a PDF above, or add one by hand." : "This quiz has no questions."}
        </div>
      ) : (
        <ol className="space-y-4">
          {questions.map((q, index) => (
            <li key={q.key}>
              <QuestionCard
                index={index}
                total={questions.length}
                question={q}
                error={errors[index]}
                editable={editable}
                onChange={(patch) => update(q.key, patch)}
                onDelete={() => remove(q.key)}
                onMove={(delta) => move(index, delta)}
              />
            </li>
          ))}
        </ol>
      )}

      <Dialog open={previewing} onOpenChange={setPreviewing}>
        <DialogContent className="max-h-[calc(100dvh-2rem)] overflow-y-auto sm:max-w-2xl">
          <DialogHeader>
            <DialogTitle>Quiz preview</DialogTitle>
            <DialogDescription>How students will see the questions. The correct answer is highlighted for you.</DialogDescription>
          </DialogHeader>
          <ol className="space-y-6">
            {questions.map((q, i) => (
              <li key={q.key} className="space-y-2">
                <p className="font-medium">
                  {i + 1}. {q.question || <span className="text-muted-foreground">(empty question)</span>}
                </p>
                <ul className="space-y-1.5">
                  {CHOICES.map((c) => (
                    <li key={c} className={cn("flex items-start gap-2 rounded-lg border px-3 py-2 text-sm", q.correctAnswer === c && "border-success bg-success/10")}>
                      <span className="font-mono font-semibold">{c}.</span>
                      <span>{q[optionField[c]] || "—"}</span>
                      {q.correctAnswer === c ? <Check className="text-success ml-auto size-4 shrink-0" aria-label="Correct answer" /> : null}
                    </li>
                  ))}
                </ul>
              </li>
            ))}
          </ol>
        </DialogContent>
      </Dialog>
    </div>
  );
}

function QuestionCard({
  index,
  total,
  question: q,
  error,
  editable,
  onChange,
  onDelete,
  onMove,
}: {
  index: number;
  total: number;
  question: EditableQuestion;
  error: string | null;
  editable: boolean;
  onChange: (patch: Partial<EditableQuestion>) => void;
  onDelete: () => void;
  onMove: (delta: -1 | 1) => void;
}) {
  const id = `q-${q.key}`;
  return (
    <Card className={cn(error && editable && "border-destructive/60")}>
      <CardContent className="space-y-4">
        <div className="flex flex-wrap items-center gap-2">
          <span className="bg-brand-indigo/12 text-brand-indigo flex size-7 items-center justify-center rounded-full text-sm font-semibold">{index + 1}</span>
          {q.fromAI ? (
            <Badge variant="secondary" className="gap-1">
              <Sparkles className="size-3" aria-hidden="true" /> AI generated · review me
            </Badge>
          ) : null}
          {editable ? (
            <div className="ml-auto flex gap-1">
              <Button variant="ghost" size="icon-sm" disabled={index === 0} onClick={() => onMove(-1)} aria-label={`Move question ${index + 1} up`}>
                <ArrowUp className="size-4" aria-hidden="true" />
              </Button>
              <Button variant="ghost" size="icon-sm" disabled={index === total - 1} onClick={() => onMove(1)} aria-label={`Move question ${index + 1} down`}>
                <ArrowDown className="size-4" aria-hidden="true" />
              </Button>
              <Button variant="ghost" size="icon-sm" className="text-destructive hover:text-destructive" onClick={onDelete} aria-label={`Delete question ${index + 1}`}>
                <Trash2 className="size-4" aria-hidden="true" />
              </Button>
            </div>
          ) : null}
        </div>

        <div className="space-y-2">
          <Label htmlFor={`${id}-text`}>Question</Label>
          <textarea
            id={`${id}-text`}
            rows={2}
            value={q.question}
            disabled={!editable}
            onChange={(event) => onChange({ question: event.target.value })}
            className="border-input bg-background focus-visible:border-ring focus-visible:ring-ring/50 disabled:opacity-70 min-h-16 w-full rounded-md border px-3 py-2 text-sm outline-none focus-visible:ring-3"
          />
        </div>

        <fieldset className="space-y-2" disabled={!editable}>
          <legend className="text-sm font-medium">Options — select the correct one</legend>
          <div className="grid gap-2 sm:grid-cols-2">
            {CHOICES.map((c) => {
              const correct = q.correctAnswer === c;
              return (
                <div key={c} className={cn("flex items-center gap-2 rounded-lg border p-2 transition-colors", correct && "border-success bg-success/10")}>
                  <button
                    type="button"
                    role="radio"
                    aria-checked={correct}
                    aria-label={`Option ${c} is the correct answer`}
                    onClick={() => onChange({ correctAnswer: c })}
                    className={cn(
                      "focus-visible:ring-ring/50 flex size-7 shrink-0 items-center justify-center rounded-full border text-xs font-semibold outline-none focus-visible:ring-3",
                      correct ? "border-success bg-success text-white" : "text-muted-foreground hover:bg-muted",
                    )}
                  >
                    {correct ? <Check className="size-4" aria-hidden="true" /> : c}
                  </button>
                  <Input
                    value={q[optionField[c]]}
                    aria-label={`Option ${c}`}
                    onChange={(event) => onChange({ [optionField[c]]: event.target.value } as Partial<EditableQuestion>)}
                    className="h-9 border-0 bg-transparent shadow-none focus-visible:ring-0"
                  />
                </div>
              );
            })}
          </div>
        </fieldset>

        <div className="grid gap-4 sm:grid-cols-[2fr_1fr]">
          <div className="space-y-2">
            <Label htmlFor={`${id}-exp`}>Explanation</Label>
            <textarea
              id={`${id}-exp`}
              rows={2}
              value={q.explanation}
              disabled={!editable}
              onChange={(event) => onChange({ explanation: event.target.value })}
              className="border-input bg-background focus-visible:border-ring focus-visible:ring-ring/50 disabled:opacity-70 w-full rounded-md border px-3 py-2 text-sm outline-none focus-visible:ring-3"
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor={`${id}-src`}>Source</Label>
            <Input id={`${id}-src`} value={q.sourceReference} disabled={!editable} placeholder="e.g. Page 4" onChange={(event) => onChange({ sourceReference: event.target.value })} className="h-9" />
          </div>
        </div>

        {error && editable ? (
          <p role="alert" className="text-destructive flex items-center gap-1.5 text-sm">
            <CircleAlert className="size-4" aria-hidden="true" /> {error}
          </p>
        ) : null}
      </CardContent>
    </Card>
  );
}

function AiGenerator({ quiz, onGenerated }: { quiz: QuizDetail; onGenerated: (questions: EditableQuestion[]) => void }) {
  const materials = useApiQuery({
    queryKey: queryKeys.course.materials(quiz.courseOfferingId),
    queryFn: () => materialApi.list(quiz.courseOfferingId),
  });
  const [materialId, setMaterialId] = useState(quiz.material?.id ?? "");
  const [count, setCount] = useState("10");
  const [difficulty, setDifficulty] = useState<"easy" | "medium" | "hard">("medium");
  const [result, setResult] = useState<{ count: number; warnings: string[] } | null>(null);
  const [startedAt, setStartedAt] = useState<number | null>(null);

  const selected = materialId || materials.data?.[0]?.id || "";

  const generate = useApiMutation({
    mutationFn: () => aiApi.generateQuiz({ offeringId: quiz.courseOfferingId, materialId: selected, numberOfQuestions: Number(count), difficulty }),
    notifyError: false,
    onSuccess: (data) => {
      setResult({ count: data.questions.length, warnings: data.warnings });
      onGenerated(data.questions.map((q) => toEditable(q, true)));
      // Remember which PDF these came from (best effort: not worth failing over).
      if (selected && selected !== quiz.material?.id) void quizApi.update(quiz.id, { materialId: selected }).catch(() => undefined);
    },
  });

  const noMaterials = materials.isSuccess && materials.data.length === 0;

  return (
    <Card className="border-brand-violet/30 bg-brand-violet/[0.03]">
      <CardContent className="space-y-4">
        <div className="flex items-start gap-3">
          <span className="bg-brand-violet/12 text-brand-violet flex size-10 shrink-0 items-center justify-center rounded-xl">
            <Sparkles className="size-5" aria-hidden="true" />
          </span>
          <div>
            <h2 className="text-base font-semibold">Generate MCQs with AI</h2>
            <p className="text-muted-foreground text-sm">Questions are written only from the PDF you pick. You review and edit every one before saving; nothing reaches students until you publish.</p>
          </div>
        </div>

        {noMaterials ? (
          <p className="text-muted-foreground text-sm">Upload a PDF in this course’s Materials tab first.</p>
        ) : (
          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-[2fr_1fr_auto] lg:items-end">
            <div className="space-y-2">
              <Label htmlFor="ai-material">Source PDF</Label>
              <Select value={selected} onValueChange={setMaterialId} disabled={generate.isPending}>
                <SelectTrigger id="ai-material" className="h-10 w-full">
                  <SelectValue placeholder={materials.isPending ? "Loading…" : "Choose a PDF"} />
                </SelectTrigger>
                <SelectContent>
                  {(materials.data ?? []).map((m) => (
                    <SelectItem key={m.id} value={m.id}>
                      {m.title}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label htmlFor="ai-count">Number of questions</Label>
              <Select value={count} onValueChange={setCount} disabled={generate.isPending}>
                <SelectTrigger id="ai-count" className="h-10 w-full">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {COUNTS.map((c) => (
                    <SelectItem key={c} value={c}>
                      {c}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2 sm:col-span-2 lg:col-span-1">
              <span className="text-sm font-medium" id="ai-difficulty-label">
                Difficulty
              </span>
              <div role="radiogroup" aria-labelledby="ai-difficulty-label" className="flex gap-1.5">
                {DIFFICULTIES.map((d) => (
                  <Button key={d.value} type="button" role="radio" aria-checked={difficulty === d.value} variant={difficulty === d.value ? "default" : "outline"} size="sm" disabled={generate.isPending} onClick={() => setDifficulty(d.value)}>
                    {d.label}
                  </Button>
                ))}
              </div>
            </div>
            <Button
              disabled={!selected || generate.isPending}
              onClick={() => {
                setResult(null);
                setStartedAt(Date.now());
                generate.mutate();
              }}
              className="bg-brand-gradient h-10 text-white hover:opacity-90 sm:col-span-2 lg:col-span-3"
            >
              {generate.isPending ? (
                <>
                  <Loader2 className="size-4 animate-spin" aria-hidden="true" /> Generating…
                </>
              ) : (
                <>
                  <Sparkles className="size-4" aria-hidden="true" /> Generate MCQ with AI
                </>
              )}
            </Button>
          </div>
        )}

        {generate.isPending && startedAt ? <GenerationProgress startedAt={startedAt} /> : null}

        {generate.isError ? <FormAlert message={generate.error.message} details={[]} /> : null}

        {result ? (
          <div role="status" className="bg-success/10 text-foreground rounded-lg border border-success/30 p-3 text-sm">
            <p className="font-medium">
              {result.count} question(s) added below. Review them, edit anything that is off, then save.
            </p>
            {result.warnings.length > 0 ? (
              <ul className="text-muted-foreground mt-1 list-disc pl-5">
                {result.warnings.map((w) => (
                  <li key={w}>{w}</li>
                ))}
              </ul>
            ) : null}
          </div>
        ) : null}
      </CardContent>
    </Card>
  );
}

/** Honest staged feedback while the server works: the stage advances with elapsed time. */
function GenerationProgress({ startedAt }: { startedAt: number }) {
  const now = useNow(500);
  const elapsed = Math.max(0, (now - startedAt) / 1000);
  const stage = Math.min(STAGES.length - 1, Math.floor(elapsed / 7));

  return (
    <div className="space-y-3" role="status" aria-live="polite">
      <p className="text-sm font-medium">Generating questions from your course material…</p>
      <Progress value={Math.min(95, 8 + elapsed * 3)} aria-label="Generation progress" />
      <ul className="text-muted-foreground space-y-1 text-sm">
        {STAGES.map((label, i) => (
          <li key={label} className={cn("flex items-center gap-2", i === stage && "text-foreground font-medium")}>
            {i < stage ? <Check className="text-success size-4" aria-hidden="true" /> : i === stage ? <Loader2 className="size-4 animate-spin" aria-hidden="true" /> : <span className="size-4" aria-hidden="true" />}
            {label}
          </li>
        ))}
      </ul>
      <p className="text-muted-foreground text-xs">This can take up to a minute for long PDFs.</p>
    </div>
  );
}

